# Generated by Django 3.2.6 on 2021-09-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Slide2.jpg', null=True, upload_to=''),
        ),
    ]
